name: MLOps CI Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  train:

    runs-on: ubuntu-latest

    steps:

    - name: Run actions/checkout@v3
      uses: actions/checkout@v4

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: mlflow-env
        python-version: 3.12
        auto-activate-base: false

    - name: Check conda
      run: |
        which conda
        conda --version
    - name: Setup Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Check Env
      run: |
        python --version
        pip --version
        pwd

    - name: Install Dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn matplotlib

    - name: Debug
      run: |
          ls -la MLProject
          cat MLProject/MLproject
    - name: Debug Conda Shell
      run: |
        which conda
        conda env list
        conda info
        type conda
    - name: Test Conda Activation
      shell: bash -l {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate mlflow-env
        python --version
       
    - name: Run MLflow Project
      env: 
        MLFLOW_ALLOW_FILE_STORE: "true"
      run: |
        mlflow run $GITHUB_WORKSPACE/MLProject --env-manager=local

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker Model
      run: |
        docker build -t teen-mental-health .

    - name: Tag Docker Image
      run: |
        docker tag \
        teen-mental-health \
        ${{ secrets.DOCKER_HUB_USERNAME }}/teen-mental-health:latest

    - name: Push Image Docker
      run: |
        docker push \
        ${{ secrets.DOCKER_HUB_USERNAME }}/teen-mental-health:latest
